export interface userResponse{
    code: number,
    status: boolean,
    message: string,
    data: {
        first_name:string,
        last_name:string,
        username:string,
        user_email:string,
        billing_first_name:string,
        billing_last_name:string,
        billing_company:string,
        billing_country:string,
        billing_address_1:string,
        billing_address_2:string,
        billing_city:string,
        billing_state:string,
        billing_postcode:string,
        billing_phone:string,
        billing_email:string,
        shipping_first_name:string,
        shipping_last_name:string,
        shipping_company:string,
        shipping_country:string,
        shipping_address_1:string,
        shipping_address_2:string,
        shipping_city:string,
        shipping_state:string,
    }
}